services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      # Режим KRaft, без Zookeeper
      - KAFKA_CFG_NODE_ID=0 # Уникальный идентификатор брокера
      - KAFKA_CFG_PROCESS_ROLES=controller,broker # Роли процесса, одна нода выполняет сразу 2 роли
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 # Слушатели для клиентских и контроллерских соединений 
      # (PLAINTEXT://:9092 — клиентские подключения (producer/consumer), CONTROLLER://:9093 — внутренние сообщения контроллера (KRaft).)
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093 # для контроллерного (controller-to-controller) трафика используйте listener с именем CONTROLLER
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  # контроллеры будут связываться через listener с именем CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 # ключевая переменная для клиентов (консьюмер/продьюсер)
      # используется, чтобы клиенты (вне контейнера) знали, на какой адрес подключаться, тк порты внутри контейнера свои
    volumes:
      - 'kafka_data:/bitnami/kafka'
# NB) Listener - это настройка в конфигурации брокера, 
# которая описывает сетевой интерфейс (адрес:порт) и имя, на котором этот брокер принимает соединения.

volumes:
  postgres_data:
    driver: local
  kafka_data:
    driver: local